"""empty message

Revision ID: 2b224335ba37
Revises: 3d8798dc99fa
Create Date: 2016-07-05 15:34:38.578626

"""

# revision identifiers, used by Alembic.
revision = '2b224335ba37'
down_revision = '3d8798dc99fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('net_weight', sa.Float(), nullable=False),
    sa.Column('gross_weight_per_box', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_info_count'), 'item_info', ['count'], unique=False)
    op.create_index(op.f('ix_item_info_name'), 'item_info', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_info_name'), table_name='item_info')
    op.drop_index(op.f('ix_item_info_count'), table_name='item_info')
    op.drop_table('item_info')
    ### end Alembic commands ###
