"""empty message

Revision ID: 2ccb1893c8c0
Revises: 3353d3dfc2dd
Create Date: 2019-08-29 17:23:02.398855

"""

# revision identifiers, used by Alembic.
revision = '2ccb1893c8c0'
down_revision = '3353d3dfc2dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('external_order_no', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'external_order_no')
    ### end Alembic commands ###
