"""empty message

Revision ID: 3353d3dfc2dd
Revises: deac445d1a44
Create Date: 2018-12-05 22:18:23.335051

"""

# revision identifiers, used by Alembic.
revision = '3353d3dfc2dd'
down_revision = 'deac445d1a44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('discarded_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'discarded_time')
    ### end Alembic commands ###
