"""empty message

Revision ID: 3e85e5b1b1c2
Revises: 2ccb1893c8c0
Create Date: 2019-08-29 17:28:49.330293

"""

# revision identifiers, used by Alembic.
revision = '3e85e5b1b1c2'
down_revision = '2ccb1893c8c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('external_order_no', sa.String(length=64), nullable=True))
    op.add_column('order', sa.Column('external_package_no', sa.String(length=64), nullable=True))
    op.drop_column('order', 'external_order_no')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('external_order_no', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('order', 'external_package_no')
    op.drop_column('job', 'external_order_no')
    ### end Alembic commands ###
