"""empty message

Revision ID: 42c70a9f733b
Revises: b4f6287bd43a
Create Date: 2017-03-04 15:09:15.089307

"""

# revision identifiers, used by Alembic.
revision = '42c70a9f733b'
down_revision = 'b4f6287bd43a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('bc_measurement_unit', sa.String(length=64), nullable=True))
    op.add_column('product_info', sa.Column('bc_product_code', sa.String(length=64), nullable=True))
    op.add_column('product_info', sa.Column('bc_second_measurement_unit', sa.String(length=64), nullable=True))
    op.add_column('product_info', sa.Column('bc_second_quantity', sa.String(length=64), nullable=True))
    op.add_column('product_info', sa.Column('bc_specification', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_info', 'bc_specification')
    op.drop_column('product_info', 'bc_second_quantity')
    op.drop_column('product_info', 'bc_second_measurement_unit')
    op.drop_column('product_info', 'bc_product_code')
    op.drop_column('product_info', 'bc_measurement_unit')
    ### end Alembic commands ###
