"""empty message

Revision ID: 45dafd83a675
Revises: 752d3ba4b38d
Create Date: 2016-06-29 16:11:55.513535

"""

# revision identifiers, used by Alembic.
revision = '45dafd83a675'
down_revision = '752d3ba4b38d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_time', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.String(length=256), nullable=True),
    sa.Column('receiver', sa.String(length=256), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_order_number'), 'order', ['order_number'], unique=True)
    op.create_index(op.f('ix_order_type'), 'order', ['type'], unique=False)
    op.create_index(op.f('ix_order_used'), 'order', ['used'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_used'), table_name='order')
    op.drop_index(op.f('ix_order_type'), table_name='order')
    op.drop_index(op.f('ix_order_order_number'), table_name='order')
    op.drop_table('order')
    ### end Alembic commands ###
