"""empty message

Revision ID: 4da2bbd83dac
Revises: d80d352547bd
Create Date: 2016-07-05 15:53:00.894510

"""

# revision identifiers, used by Alembic.
revision = '4da2bbd83dac'
down_revision = 'd80d352547bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product_info', ['name', 'count'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_info', type_='unique')
    ### end Alembic commands ###
