"""empty message

Revision ID: 537e58ea8d6c
Revises: 8a3679db4c14
Create Date: 2016-07-07 17:02:00.250654

"""

# revision identifiers, used by Alembic.
revision = '537e58ea8d6c'
down_revision = '8a3679db4c14'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retraction', sa.Column('success', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retraction', 'success')
    ### end Alembic commands ###
