"""empty message

Revision ID: 538b45d48161
Revises: b22a81cbf0e7
Create Date: 2016-07-07 13:53:10.715088

"""

# revision identifiers, used by Alembic.
revision = '538b45d48161'
down_revision = 'b22a81cbf0e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('retracted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'retracted')
    ### end Alembic commands ###
