"""empty message

Revision ID: 65b0c6d89f7a
Revises: 4ad256887635
Create Date: 2017-01-19 16:43:06.663109

"""

# revision identifiers, used by Alembic.
revision = '65b0c6d89f7a'
down_revision = '4ad256887635'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('specification', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_info', 'specification')
    ### end Alembic commands ###
