"""empty message

Revision ID: 752d3ba4b38d
Revises: f1a78264dd37
Create Date: 2016-06-22 11:23:01.851436

"""

# revision identifiers, used by Alembic.
revision = '752d3ba4b38d'
down_revision = 'f1a78264dd37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('name', sa.String(length=32), nullable=False))
    op.add_column('city', sa.Column('type', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=False)
    op.create_index(op.f('ix_city_type'), 'city', ['type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_type'), table_name='city')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_column('city', 'type')
    op.drop_column('city', 'name')
    ### end Alembic commands ###
