"""empty message

Revision ID: 890afc26bb1b
Revises: None
Create Date: 2016-06-11 16:36:17.369319

"""

# revision identifiers, used by Alembic.
revision = '890afc26bb1b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_uuid'), 'job', ['uuid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_uuid'), table_name='job')
    op.drop_table('job')
    ### end Alembic commands ###
