"""empty message

Revision ID: 9aa069b2417d
Revises: None
Create Date: 2016-08-22 15:22:08.772102

"""

# revision identifiers, used by Alembic.
revision = '9aa069b2417d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=False)
    op.create_index(op.f('ix_city_type'), 'city', ['type'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('completion_time', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_uuid'), 'job', ['uuid'], unique=True)
    op.create_table('product_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('net_weight', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_info_name'), 'product_info', ['name'], unique=True)
    op.create_table('retraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retraction_uuid'), 'retraction', ['uuid'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('reset_password_token', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_time', sa.DateTime(), nullable=True),
    sa.Column('sender_address', sa.String(length=256), nullable=True),
    sa.Column('receiver_address', sa.String(length=256), nullable=True),
    sa.Column('receiver_name', sa.String(length=32), nullable=True),
    sa.Column('receiver_id_number', sa.String(length=64), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('retraction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['retraction_id'], ['retraction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_order_number'), 'order', ['order_number'], unique=True)
    op.create_index(op.f('ix_order_type'), 'order', ['type'], unique=False)
    op.create_index(op.f('ix_order_used'), 'order', ['used'], unique=False)
    op.create_table('product_count_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_info_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('gross_weight_per_box', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_info_id'], ['product_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_info_id', 'count')
    )
    op.create_index(op.f('ix_product_count_info_count'), 'product_count_info', ['count'], unique=False)
    op.create_index(op.f('ix_product_count_info_product_info_id'), 'product_count_info', ['product_info_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_count_info_product_info_id'), table_name='product_count_info')
    op.drop_index(op.f('ix_product_count_info_count'), table_name='product_count_info')
    op.drop_table('product_count_info')
    op.drop_index(op.f('ix_order_used'), table_name='order')
    op.drop_index(op.f('ix_order_type'), table_name='order')
    op.drop_index(op.f('ix_order_order_number'), table_name='order')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_index(op.f('ix_retraction_uuid'), table_name='retraction')
    op.drop_table('retraction')
    op.drop_index(op.f('ix_product_info_name'), table_name='product_info')
    op.drop_table('product_info')
    op.drop_index(op.f('ix_job_uuid'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_city_type'), table_name='city')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_table('city')
    ### end Alembic commands ###
