"""empty message

Revision ID: a4221c978242
Revises: 848579ac24cb
Create Date: 2018-08-22 20:58:56.046751

"""

# revision identifiers, used by Alembic.
revision = 'a4221c978242'
down_revision = '848579ac24cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_name'), 'route', ['name'], unique=True)
    op.create_table('product_routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('product_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_info_id'], ['product_info.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'product_info_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_routes')
    op.drop_index(op.f('ix_route_name'), table_name='route')
    op.drop_table('route')
    ### end Alembic commands ###
