"""empty message

Revision ID: aa922fbc22b7
Revises: 9aa069b2417d
Create Date: 2016-11-07 14:45:13.257662

"""

# revision identifiers, used by Alembic.
revision = 'aa922fbc22b7'
down_revision = '9aa069b2417d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('receiver_mobile', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'receiver_mobile')
    ### end Alembic commands ###
