"""empty message

Revision ID: b22a81cbf0e7
Revises: 4da2bbd83dac
Create Date: 2016-07-05 16:41:14.372918

"""

# revision identifiers, used by Alembic.
revision = 'b22a81cbf0e7'
down_revision = '4da2bbd83dac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_count_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_info_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('gross_weight_per_box', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_info_id'], ['product_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_info_id', 'count')
    )
    op.create_index(op.f('ix_product_count_info_count'), 'product_count_info', ['count'], unique=False)
    op.create_index(op.f('ix_product_count_info_product_info_id'), 'product_count_info', ['product_info_id'], unique=False)
    op.drop_index('ix_product_info_name', table_name='product_info')
    op.create_index(op.f('ix_product_info_name'), 'product_info', ['name'], unique=True)
    op.drop_index('ix_product_info_count', table_name='product_info')
    op.drop_constraint(u'product_info_name_count_key', 'product_info', type_='unique')
    op.drop_column(u'product_info', 'count')
    op.drop_column(u'product_info', 'gross_weight_per_box')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'product_info', sa.Column('gross_weight_per_box', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column(u'product_info', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(u'product_info_name_count_key', 'product_info', ['name', 'count'])
    op.create_index('ix_product_info_count', 'product_info', ['count'], unique=False)
    op.drop_index(op.f('ix_product_info_name'), table_name='product_info')
    op.create_index('ix_product_info_name', 'product_info', ['name'], unique=False)
    op.drop_index(op.f('ix_product_count_info_product_info_id'), table_name='product_count_info')
    op.drop_index(op.f('ix_product_count_info_count'), table_name='product_count_info')
    op.drop_table('product_count_info')
    ### end Alembic commands ###
