"""empty message

Revision ID: b4f6287bd43a
Revises: 486a4b255e0e
Create Date: 2017-03-04 13:26:28.751271

"""

# revision identifiers, used by Alembic.
revision = 'b4f6287bd43a'
down_revision = '486a4b255e0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_info', 'full_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_index(op.f('ix_product_info_full_name'), 'product_info', ['full_name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_info_full_name'), table_name='product_info')
    op.alter_column('product_info', 'full_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    ### end Alembic commands ###
