"""empty message

Revision ID: d80d352547bd
Revises: 2b224335ba37
Create Date: 2016-07-05 15:37:36.010766

"""

# revision identifiers, used by Alembic.
revision = 'd80d352547bd'
down_revision = '2b224335ba37'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('net_weight', sa.Float(), nullable=False),
    sa.Column('gross_weight_per_box', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_info_count'), 'product_info', ['count'], unique=False)
    op.create_index(op.f('ix_product_info_name'), 'product_info', ['name'], unique=False)
    op.drop_table('item_info')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('net_weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gross_weight_per_box', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price_per_kg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('deprecated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'item_info_pkey')
    )
    op.drop_index(op.f('ix_product_info_name'), table_name='product_info')
    op.drop_index(op.f('ix_product_info_count'), table_name='product_info')
    op.drop_table('product_info')
    ### end Alembic commands ###
