"""empty message

Revision ID: e5bda1b08598
Revises: 3e85e5b1b1c2
Create Date: 2019-12-06 16:02:46.872168

"""

# revision identifiers, used by Alembic.
revision = 'e5bda1b08598'
down_revision = '3e85e5b1b1c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retraction', sa.Column('custom_clearance_time', sa.DateTime(), nullable=True))
    op.add_column('retraction', sa.Column('landed_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retraction', 'landed_time')
    op.drop_column('retraction', 'custom_clearance_time')
    ### end Alembic commands ###
