"""empty message

Revision ID: f1a78264dd37
Revises: 37918676d545
Create Date: 2016-06-22 11:16:55.611184

"""

# revision identifiers, used by Alembic.
revision = 'f1a78264dd37'
down_revision = '37918676d545'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
