"""empty message

Revision ID: f345cca3f384
Revises: 890afc26bb1b
Create Date: 2016-06-11 16:52:18.424466

"""

# revision identifiers, used by Alembic.
revision = 'f345cca3f384'
down_revision = '890afc26bb1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('completion_time', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('creation_time', sa.DateTime(), nullable=True))
    op.add_column('job', sa.Column('message', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'message')
    op.drop_column('job', 'creation_time')
    op.drop_column('job', 'completion_time')
    ### end Alembic commands ###
